name: angel_helmet
version: 0.0.0
description: A collection of 11 middleware and handlers to help secure your application using HTTP headers.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/helmet
dependencies:
  angel_framework: ^1.0.0-dev
dev_dependencies:
  angel_test: ^1.0.0-dev
  test: ^0.12.0